### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by tim-pl-m** [hellokoding/dockercompose-springboot-mongodb-nginx#1]
on OSX the app cant connect to mongo-db:
```
app_1      | 2019-07-05 09:53:49.933  INFO 1 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
app_1      | 2019-07-05 09:53:50.019  INFO 1 --- [localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017
app_1      | 
app_1      | com.mongodb.MongoSocketOpenException: Exception opening socket
app_1      | 	at com.mongodb.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.6.1.jar:na]
app_1      | 	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.6.1.jar:na]
app_1      | 	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:114) ~[mongodb-driver-core-3.6.1.jar:na]
app_1      | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
app_1      | Caused by: java.net.ConnectException: Connection refused (Connection refused)
app_1      | 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_181]
app_1      | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_181]
app_1      | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_181]
app_1      | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_181]
app_1      | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_181]
app_1      | 	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_181]
app_1      | 	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:59) ~[mongodb-driver-core-3.6.1.jar:na]
app_1      | 	at com.mongodb.connection.SocketStream.open(SocketStream.java:57) ~[mongodb-driver-core-3.6.1.jar:na]
app_1      | 	... 3 common frames omitted
```

but connecting to mongo via shell works:
```
mongo
MongoDB shell version v4.0.3
connecting to: mongodb://127.0.0.1:27017
Implicit session: session { "id" : UUID("28e23890-dd7d-4c02-b128-d3b8841cff2d") }
MongoDB server version: 3.6.13
WARNING: shell and server versions do not match
Server has startup warnings: 
2019-07-05T09:53:42.142+0000 I CONTROL  [initandlisten] 
2019-07-05T09:53:42.142+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2019-07-05T09:53:42.142+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2019-07-05T09:53:42.142+0000 I CONTROL  [initandlisten] 
> 
```

somebody an idea?

PS:
spring.data.mongodb.host: 127.0.0.1 in app/src/main/resources/application.yaml
doesnt help:
`app_1      | 2019-07-05 10:04:15.088  INFO 1 --- [127.0.0.1:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server 127.0.0.1:27017
app_1      | 
app_1      | com.mongodb.MongoSocketOpenException: Exception opening socket
`

PPS:
same problem, no explicit solution:
https://stackoverflow.com/questions/45742999/com-mongodb-mongosocketopenexception-exception-opening-socketmongodb-docker

**Comment by tim-pl-m** [comment]
fixed.
see comment:
https://stackoverflow.com/questions/45742999/com-mongodb-mongosocketopenexception-exception-opening-socketmongodb-docker/56906060#56906060
or my fork :)
